apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: itshops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: minhdv20/e-commerce-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: host.docker.internal
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "2002"
            - name: MYSQL_DATABASE
              value: itshopsdata
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: itshops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: minhdv20/e-commerce-frontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
