version: '3.8'

services:
  frontend:
    build:
      context: ./Itshops
      dockerfile: dockerfile
    ports:
      - "3000:80"
    restart: always

  backend:
    build:
      context: ./server
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: root
      MYSQL_PASSWORD: 2002
      MYSQL_DATABASE: itshopsdata
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app