services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2002
      MYSQL_DATABASE: itshopsdata
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Mount dữ liệu vào volume "mysql_data"
    restart: always
    
  backend:
    build:
      context: ./server
    image: minhdv20/e-commerce-backend:latest
    container_name: backend
    environment:
      MYSQL_HOST: mysql            # Tên container MySQL
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 2002
      MYSQL_DATABASE: itshopsdata
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app  # Volume này chỉ mount code từ máy chủ vào container
    depends_on:
      - mysql
    restart: always

  frontend:
    build:
      context: ./Itshops
      dockerfile: dockerfile
    image: minhdv20/e-commerce-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:  # Khai báo volume "mysql_data" để lưu trữ dữ liệu lâu dài
