apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: itshop
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # nodePort: 31001

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: itshop
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30002
